name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer Cython==0.29.33

      - name: Run Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # On force le build sans poser de questions
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "y"

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MonJeu-APK
          path: bin/*.apk
